# Generated by Django 3.1.4 on 2021-05-25 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=30, unique=True)),
                ('address', models.CharField(default='保定', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('name', models.CharField(choices=[('C', '客户'), ('CM', '客户经理'), ('S', '客服'), ('SM', '客服经理'), ('F', '冻结用户')], max_length=2, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('phone', models.CharField(max_length=11)),
                ('status', models.CharField(default='启用', max_length=50)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.group')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='crm.role')),
            ],
        ),
        migrations.CreateModel(
            name='PausedDistrict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=30)),
                ('area', models.TextField(blank=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('redactor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='crm.user')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zto_number', models.CharField(db_index=True, max_length=30, unique=True)),
                ('question_types', models.CharField(choices=[('LJ', '拦截'), ('GDZ', '改地址'), ('CP', '催派'), ('YS', '签收未收到'), ('CX', '查询')], max_length=3)),
                ('question_text', models.TextField(max_length=300)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('order_status', models.IntegerField(choices=[(1, '待处理'), (2, '处理中'), (3, '待审核'), (4, '已关闭')], default=1)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='crm.user')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.group')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service', to='crm.user')),
            ],
        ),
        migrations.CreateModel(
            name='Handover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('handover_text', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.group')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='recipient', to='crm.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='the_handover', to='crm.user')),
            ],
            options={
                'get_latest_by': 'pub_date',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(max_length=300)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='crm.user')),
            ],
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='通知', max_length=100)),
                ('notice', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='crm.user')),
            ],
            options={
                'get_latest_by': 'pub_date',
            },
        ),
    ]
