# Generated by Django 3.1.4 on 2021-05-26 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('C', '客户'), ('CM', '客户经理'), ('S', '客服'), ('SM', '客服经理')], max_length=2, primary_key=True, serialize=False),
        ),
    ]
