# Generated by Django 3.1.4 on 2021-06-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20210526_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_emergency',
            field=models.IntegerField(choices=[(1, '加急'), (2, '待回复'), (3, '已回复')], default=2),
        ),
        migrations.AddField(
            model_name='order',
            name='reply_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='question_types',
            field=models.CharField(choices=[('LJ', '拦截'), ('GDZ', '改地址'), ('CP', '催派'), ('YS', '签收未收到'), ('CX', '查询'), ('CTI', '取消改地址')], max_length=3),
        ),
    ]
