# Generated by Django 3.1.4 on 2021-06-15 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_shop_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='handover',
            name='group',
        ),
    ]
